// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZNaAiE_wOZdBq45j4ftqzlIYVfk-RU60',
    appId: '1:174979934876:web:a42b1c81a0c9518ce6db59',
    messagingSenderId: '174979934876',
    projectId: 'attendancetracker-fa9db',
    authDomain: 'attendancetracker-fa9db.firebaseapp.com',
    storageBucket: 'attendancetracker-fa9db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4-0Vm-E89VjXNSGNn1KQI9i5mdUXDwo',
    appId: '1:174979934876:android:ae9ab785f6a610bde6db59',
    messagingSenderId: '174979934876',
    projectId: 'attendancetracker-fa9db',
    storageBucket: 'attendancetracker-fa9db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg3V7TSoZAdp8A6cYpBHx-8VaiQOhll-Q',
    appId: '1:174979934876:ios:7ca69ec27cc4aa0ce6db59',
    messagingSenderId: '174979934876',
    projectId: 'attendancetracker-fa9db',
    storageBucket: 'attendancetracker-fa9db.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg3V7TSoZAdp8A6cYpBHx-8VaiQOhll-Q',
    appId: '1:174979934876:ios:7ca69ec27cc4aa0ce6db59',
    messagingSenderId: '174979934876',
    projectId: 'attendancetracker-fa9db',
    storageBucket: 'attendancetracker-fa9db.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZNaAiE_wOZdBq45j4ftqzlIYVfk-RU60',
    appId: '1:174979934876:web:559f1707871203a4e6db59',
    messagingSenderId: '174979934876',
    projectId: 'attendancetracker-fa9db',
    authDomain: 'attendancetracker-fa9db.firebaseapp.com',
    storageBucket: 'attendancetracker-fa9db.firebasestorage.app',
  );
}
